// src/controllers/Payroll/payrollExportController.js
//
// BB-066 fetch/download follow-up: read-only access to the payroll JSON
// generated by payrollExportService.js when a cutoff period is processed.
// Admin/supervisor/superadmin only — the returned payload spans every
// department that has processed for the period, not just the caller's own,
// so this is intentionally not exposed to typical (employee) users.
//
// PayrollExportBatch is a raw-SQL table (see scripts/create-payroll-archive-tables.sql).
// It's now modeled in schema.prisma too, but this still reads via $queryRaw,
// same convention as the generation side.

const { prisma } = require("@config/connection");

/**
 * GET /api/payroll-export/by-cutoff-period/:id
 *
 * :id is any single department's CutoffPeriod id for the target period —
 * the returned payload is the merged company+period JSON regardless of
 * which department's id was used to look it up.
 */
const getPayrollExportByCutoffPeriod = async (req, res) => {
  try {
    const { id } = req.params;
    const companyId = req.user.companyId;

    // Scoped to the caller's own company — mirrors findCutoffForCompany in
    // cutoffPeriodController.js, so one company's admin can never fetch
    // another company's payroll export just by guessing/incrementing an id.
    const cutoffPeriod = await prisma.cutoffPeriod.findFirst({
      where: {
        id,
        OR: [{ companyId }, { creator: { companyId } }],
      },
      select: { companyId: true, periodStart: true, periodEnd: true },
    });

    if (!cutoffPeriod) {
      return res.status(404).json({ message: "Cutoff period not found." });
    }

    const periodStartStr = cutoffPeriod.periodStart.toISOString().slice(0, 10);
    const periodEndStr   = cutoffPeriod.periodEnd.toISOString().slice(0, 10);

    const rows = await prisma.$queryRaw`
      SELECT "employeeCount", "payload", "generatedAt"
      FROM "PayrollExportBatch"
      WHERE "companyId" = ${cutoffPeriod.companyId}
        AND "periodStart" = ${periodStartStr}::date
        AND "periodEnd" = ${periodEndStr}::date
    `;

    if (!rows.length) {
      return res.status(404).json({
        message: "No payroll export has been generated for this period yet — at least one department must be marked processed first.",
      });
    }

    const batch = rows[0];
    return res.status(200).json({
      message: "Payroll export retrieved.",
      data: {
        employeeCount: batch.employeeCount,
        generatedAt: batch.generatedAt,
        payload: batch.payload,
      },
    });
  } catch (error) {
    console.error("❌ getPayrollExportByCutoffPeriod:", error);
    return res.status(500).json({ message: "Internal server error.", error: error.message });
  }
};

module.exports = { getPayrollExportByCutoffPeriod };
